### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by yavuzhankeles** [gruz/fusionpbx-api#1]
root@ofispbx:/var/www/laravel-api# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information                                                                   Updating dependencies (including require-dev)
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/laravel-api/vendor/optimus/genie/src/Repository.php on line 262

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

Script php artisan optimize handling the post-update-cmd event returned with error code 255

**Comment by gruz** [comment]
It includes https://github.com/esbenp/genie/blob/master/src/Repository.php

It seems the line

```
        return ($this->model::CREATED_AT) ? $this->model::CREATED_AT : 'created_at';
```

causes the problem. 

Strange...

**Comment by gruz** [comment]
I don't have time to experiment now. Can you please try to find a solution?

**Comment by yavuzhankeles** [comment]
I am installing via php5.6, can it arise from it?
Fusionpbx does not work with php 7.

**Comment by gruz** [comment]
Yes, I think it's the reason. But it's not FusionPBX. It's a laravel api dependant package. 

I think php 5.6 is too old to start a project nowadays.

**Comment by yavuzhankeles** [comment]
As a result I do not understand wrong.
Do we need to install the same server as Fusionpbx?

If you are installing on the same server, how will two different php versions work in the same domain?

**Comment by gruz** [comment]
Fusionpbx works with php7. It least my fusionpbx server is under php7 and it works. Why do you think it needs php 5?

And well, I don't think this repo project will be continued. It's almost decided to abandon it at my job. So there is not much possibility someone or me would continue with this. I'd like to continue, but I have no motivation. And I'm not sure there are enough users to drive it as a community. 

Everything may happen, but by now the repo`s future is in fog. So to be clear, think twice, if you are willing to invest your efforts in it. 

Or join the development it if you want and can.

**Comment by yavuzhankeles** [comment]
When I install Debian with php 7, the installation does not even work.
I need to api for CTI I wanted to use this project that you have prepared for it.

**Comment by gruz** [comment]
I used this manual to install FusionPBX.
http://docs.fusionpbx.com/en/latest/getting_started/quick_install.html

And it installed php7. I believe you should find out how to install it with php7 anyway. Php5 is dead.

I can give you my VirtualBox Debian+FusionPBX image if you need.

**Comment by yavuzhankeles** [comment]
It would be great.

**Comment by gruz** [comment]
Mail me. arygroup@gmail.com
I'm looking for some place to place the 8 GB image.

**Comment by yavuzhankeles** [comment]
I threw mail.

**Comment by inoutglobal** [comment]
root@host49-1:/var/www/laravel-api# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/gruz/architect" file could not be downloaded (HTTP/1.1 404 Not Found)


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
