### ISSUE TITLE
Undefined property: Api\User\Repositories\UserRepository::$database

### ISSUE THREAD

**Issue by krull** [gruz/fusionpbx-api#2]
Hello,

I installed your fusionpbx-api according to your install process in `readme.md`, and [have encountered the following reproducible errors](https://pastebin.com/buss56xt).

`[2017-10-28 19:56:50] local.ERROR: ErrorException: Undefined property: Api\User\Repositories\UserRepository::$database in /var/www/laravel-api/api/User/Repositories/UserRepository.php:66`

This is prompted when using the curl method of going to the /signup/ uri for user and domain creation. It is also same when Authenticated Bearer is used as well.

I have a feeling that it is the latest laravel version that is causing this issue, as a previous install I have just worked. Just wanted to give you a heads up.

BR

krull

**Comment by gruz** [comment]
Hi. I have no time and possibility to work at this repo. At least by now. Please, fix the error at your own and pull a request here if possible. Thanks.
