### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by krull** [gruz/fusionpbx-api#3]
https://github.com/gruz/fusionpbx-api/blob/27e85fffb9e09812090d6c18bce75f7fbe22d37e/api/Settings/Events/SettingWasCreated.php#L6

I see this on 5 files searching for '[Modelsxtension](https://github.com/gruz/fusionpbx-api/search?utf8=%E2%9C%93&q=Modelsxtension&type=)'

FYI.

**Comment by gruz** [comment]
Yes. But as far as I can see, that SettingsModelsxtension is never declared. I don't remember and cannot test nowadays. I think that 
```
 use Api\SettingsModelsxtension; 
```
can be removed. What do you think?

**Comment by krull** [comment]
Hey @gruz.

We're trying to update the Update function... I've forked and will try to put a PR out once we're certain we're good to go..

EDIT: [Forked Here and added alterations...](https://github.com/gruz/fusionpbx-api/compare/master...krull:master?diff=split&name=master). Pending some more cleanups.

BR

k
